### ISSUE TITLE
Fix hover effect and open full scale on touching the icon.

### ISSUE THREAD

**Issue by Rom-chik** [Rom-chik/photo-input#3]
- Instead of touching the button full scale image should be opened by touching the icon.
![Знімок екрана 2024-07-25 021634](https://github.com/user-attachments/assets/6b59633d-aaf1-4ff6-b61c-7520a278b2d2)

- Hover darking effect on SVG icon should work on the whole button including lines, not only back ground. Maybe by using peer.
![image](https://github.com/user-attachments/assets/57ef7120-3828-4d2e-8455-6c60b6f6e261)
![image](https://github.com/user-attachments/assets/3aff9d24-e07c-48bf-9d2f-c85990e5d174)

- Instead of just overlaying default SVG icon, input image should just be placed properly. And default SVG should be hidden by using **v-else**.

**Comment by Miltonbhowmick** [comment]
Hey @Rom-chik, can you elaborate the `Instead of touching the button full scale image should be opened by touching the icon` ?

**Comment by Rom-chik** [comment]
> Instead of touching the button full scale image should be opened by touching the icon.

```
      <div v-if="imagePreviewUrl" @click="toggleFullScaleImage()">
            <img ... />
        </div>
```

> Instead of just overlaying default SVG icon, input image should just be placed properly. And default SVG should be hidden by using v-else.

```
       <!-- default svg icon -->
            <svg v-if="!imagePreviewUrl" ... > <svg/>
```

> Hover darking effect on SVG icon should work on the whole button including lines, not only back ground. Maybe by using peer.

SVG fixed by @Miltonbhowmick 
```
       <!-- small clickable svg icon below TODO remake with peer instead of usual hover: -->
                <div
                    class="absolute bottom-[-10px] left-[50%] translate-x-[-50%] flex justify-center items-center bg-[#d1d5db] hover:bg-gray-400 transition duration-75 p-1 w-[32px] h-[32px] rounded-full"
                >
                    <svg
                        width="100%"
                        height="100%"
                        viewBox="-4.8 -6.8 41.60 41.60"
                        preserveAspectRatio="xMidYMid"
                    >
                        <path ... 
```
